#!/usr/bin/python
# -*- coding: utf-8 -*-
venues = [
    {
        'name': 'The Olive Bar',
        'address': '3037 Olive St.',
        'city': 'St. Louis',
        'description': "Located in downtown St. Louis in Midtown. Featuring a rooftop patio, multiple floors, the best drinks and hottest night life in St. Louis.",
        'img': 'https://firebasestorage.googleapis.com/v0/b/arch-b83e2.appspot.com/o/venue%2Folive_bar.png?alt=media&token=2835db81-12cf-4839-b9bc-d4a8e5c05881',
        'state': 'MO',
        'zip': 63103,
    }, {
        'name': "Big Daddy's on The Landing",
        'address': '118 Morgan St',
        'city': 'St. Louis',
        'description': "Host your pre-game, watch party, or post-game celebration at Big Daddy's on the Landing",
        'img': 'https://firebasestorage.googleapis.com/v0/b/arch-b83e2.appspot.com/o/venue%2Fbig_daddys.jpg?alt=media&token=7acd96fd-93d0-49db-96d3-4f608df859ce',
        'state': 'MO',
        'zip': 63102,
    }, {
        'name': 'Wheelhouse Downtown',
        'address': '1000 Spruce St.',
        'city': 'St. Louis',
        'description': "Lofty, industrial hangout with 2 bars & creative pub grub, plus weekend brunch & TVs showing sports.",
        'img': 'https://firebasestorage.googleapis.com/v0/b/arch-b83e2.appspot.com/o/venue%2Fwheelhouse.jpg?alt=media&token=00da1efb-bbe2-4602-89b9-a2fa13a69e0d',
        'state': 'MO',
        'zip': 63102,
    }, {
        'name': 'Marquee Restaurant',
        'address': '1911 Locust St.',
        'city': 'St. Louis',
        'description': 'Sleek nightspot in airy, mod digs with a full bar, 30 video screens & inventive pub grub.',
        'img': 'https://firebasestorage.googleapis.com/v0/b/arch-b83e2.appspot.com/o/venue%2Fmarquee.jpg?alt=media&token=381a2705-5c33-4113-8552-10994306ac71',
        'state': 'MO',
        'zip': 63103,
    }
]

discounts = {

    'The Olive Bar': [
        {'type': 'Free Shot', 'size': 10},
        {'type': '*%% off', 'size': 15, 'constant': 15},
    ],

    "Big Daddy's on The Landing": [],

    'Marquee Restaurant': [
        {'type': 'Free Shot', 'size': 10},
        {'type': '*%% off', 'size': 15, 'constant': 15},
    ],

    'Wheelhouse Downtown': [
        {'type': '*%% off', 'size': 5, 'constant': 15},
        {'type': '*%% off', 'size': 10, 'constant': 20},
        {'type': '*%% off', 'size': 15, 'constant': 25},
    ],

}


names = [
    'James',
    'Logan',
    'Benjamin',
    'Mason',
    'Elijah',
    'Oliver',
    'Jacob',
    'Lucas',
    'Michael',
    'Alexander',
    'Ethan',
    'Daniel',
    'Matthew',
    'Aiden',
    'Henry',
    'Joseph',
    'Jackson',
    'Samuel',
    'Sebastian',
    'David',
    'Carter',
    'Wyatt',
    'Jayden',
    'John',
    'Owen',
    'Dylan',
    'Luke',
    'Gabriel',
    'Anthony',
    'Isaac',
    'Grayson',
    'Jack',
    'Julian',
    'Levi',
    'Christopher',
    'Joshua',
    'Andrew',
    'Lincoln',
    'Mateo',
    'Ryan',
    'Jaxon',
    'Nathan',
    'Aaron',
    'Isaiah',
    'Thomas',
    'Charles',
    'Caleb',
    'Josiah',
    'Christian',
    'Hunter',
    'Eli',
    'Jonathan',
    'Connor',
    'Landon',
    'Adrian',
    'Asher',
    'Cameron',
    'Leo',
    'Theodore',
    'Jeremiah',
    'Hudson',
    'Robert',
    'Easton',
    'Nolan',
    'Nicholas',
    'Ezra',
    'Colton',
    'Angel',
    'Brayden',
    'Jordan',
    'Dominic',
    'Austin',
    'Ian',
    'Adam',
    'Elias',
    'Greyson',
    'Jose',
    'Ezekiel',
    'Carson',
    'Evan',
    'Maverick',
    'Bryson',
    'Jace',
    'Cooper',
    'Xavier',
    'Parker',
    'Roman',
    'Jason',
    'Chase',
    'Sawyer',
    ]


words = [
    'school',
    'shoes',
    'tested',
    'dead',
    'relieved',
    'celebrate',
    'giraff',
    'construct',
    'sanction',
    'juice',
    'swim',
    'waste',
    'resell',
    'exclusive',
    'acquire',
    'bored',
    'decorate',
    'enormous',
    'amazing',
    'understood',
    'impose',
    'well-to-do',
    'soap',
    'disobey',
    'division',
    'paper',
    'dazzle',
    'friend',
    'butter',
    'store',
    'chicken',
    'burly',
    'pour',
    'fascinated',
    'racial',
    'nutritious',
    'earthquake',
    'wacky',
    'license',
    'robin',
    'pick',
    'parsimonious',
    'entertain',
    'internal',
    'hum',
    'quiet',
    'stem',
    'safe',
    'stitch',
    'head',
    'mammoth',
    'beef',
    'part',
    'order',
    'boundary',
    'curtain',
    'exuberant',
    'glib',
    'measure',
    'pull',
    'plate',
    'view',
    'reflective',
    'fortunate',
    'plot',
    'sack',
    'mundane',
    'agreeable',
    'recess',
    'inform',
    'belligerent',
    'wreck',
    'sleepy',
    'domineering',
    'known',
    'appear',
    'eggnog',
    'misty',
    'pastoral',
    'star',
    ]
