# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'arch_mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  #ui stuff
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'FSCalendar'

  #Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  #Facebook
  pod 'FacebookCore'
  pod 'FacebookLogin'

  #Pusher
  pod 'PushNotifications'

end
