# Generated by Django 2.0.5 on 2018-11-03 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_transaction_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='venues', to=settings.AUTH_USER_MODEL),
        ),
    ]
